        try:
            if str(staff["user"]["phone"]) == str(phone):
                staff_id = staff["id"]
                yclients_phones.append(staff["user"]["phone"])
        except TypeError as error:
            logging.info("phone number processing error: {}".format(error))2018-09-06 15:17:27 PM finished add goods to record with record_id: 64109078
2018-09-06 15:17:28 PM finished add service to record with record_id: 64109078
2018-09-06 15:18:42 PM finished add goods to record with record_id: 64109078
2018-09-06 15:18:43 PM finished add service to record with record_id: 64109078
2018-09-06 15:19:13 PM ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/Library/Python/2.7/site-packages/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/Library/Python/2.7/site-packages/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/Library/Python/2.7/site-packages/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/Library/Python/2.7/site-packages/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]

2018-09-06 15:22:45 PM Error during photo processing: A request to the Telegram API was unsuccessful. The server returned HTTP 400 Bad Request. Response body:
[{"ok":false,"error_code":400,"description":"Bad Request: message to edit not found"}]
2018-09-06 15:24:33 PM Error during photo processing: A request to the Telegram API was unsuccessful. The server returned HTTP 400 Bad Request. Response body:
[{"ok":false,"error_code":400,"description":"Bad Request: message can't be edited"}]
2018-09-06 15:25:37 PM Error during photo processing: A request to the Telegram API was unsuccessful. The server returned HTTP 400 Bad Request. Response body:
[{"ok":false,"error_code":400,"description":"Bad Request: inline keyboard expected"}]
2018-09-06 15:27:29 PM finished add goods to record with record_id: 64109078
2018-09-06 15:27:31 PM finished add service to record with record_id: 64109078
